### PR TITLE
[Bugfix] Normalize path comparison for windows

### LINKED ISSUE #4: Package fails to find package on Windows
https://github.com/marcj/typedoc-plugin-lerna-packages/blob/6a315f476dc84c6ec64c211e7bac08c8a9d91ce7/plugin.ts#L71

Logging out the variables reveals the problem.

```ts
for (const i in this.lernaPackages) {
  if (!this.lernaPackages.hasOwnProperty(i))
    continue;
  console.log(i);
  const packagePath = path_1.join(cwd, this.lernaPackages[i]) + '/';
  console.log("packagePath:", packagePath);
  console.log("path:", path);
  if (-1 !== (path + '/').indexOf(packagePath)) {
  console.log("fit", fit);
  if (i.length > fit.length) {
    fit = i;
  }
}
```

```
@as-pect/cli
packagePath: C:\Users\jtenner\Desktop\projects\as-pect\packages\cli/
path: C:/Users/jtenner/Desktop/projects/as-pect/packages/cli/src/help.ts
@as-pect/core
packagePath: C:\Users\jtenner\Desktop\projects\as-pect\packages\core/
path: C:/Users/jtenner/Desktop/projects/as-pect/packages/cli/src/help.ts
```

As you can see, the strings aren't normalized for windows users. This can be fixed by simply calling `path.normalize()` on the `packagePath` and the `path` object.

Would you like me to submit a pull request?

### PR DESCRIPTION
**Pull request by jtenner**
fixes #4 

How would you like me to fix this request so you can use it?

### CODE REVIEW

**Comment by marcj** [comment]
Thanks. Is there a reason you want to put the js & js.map code to git?

**Comment by jtenner** [comment]
I wanted to test it locally using my dev environment.

```json
{
  "typedoc-plugin-lerna-packages": "github:jtenner/typedoc-plugin-lerna-packages"
}
```

Other than that? No. I'll fix this right away.

**Comment by marcj** [comment]
I see, to test it locally you can check it out, build it, and reference it in a project using either 

```
"typedoc-plugin-lerna-packages": "file:../my-folder-to/typedoc-plugin-lerna-packages"
```

or better use a `.links.json` using [npm-local-development](https://github.com/marcj/npm-local-development), which automatically overwrites the installed package with a locally available dev version

**Comment by marcj** [comment]
Alright, thanks!

**Comment by jtenner** [comment]
Make sure to bump the package and publish soon! Thanks for this.

**Comment by marcj** [comment]
Done 👍

**Pull request merged**
